name: Build and Deploy to ECS

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  quality-gate:
    name: Quality Gate
    uses: sergioortiz17/cicd-templates/.github/workflows/quality-gate.yml@main
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy:
    needs: quality-gate
    uses: sergioortiz17/cicd-templates/.github/workflows/ecs-build-deploy.yml@main
    with:
      app_name: java-cdk-tools-dev
      ecr_repository: java-cdk-tools-dev
      ecs_cluster: dev-cluster
      ecs_service: java-cdk-tools-dev-service
      aws_region: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
